import type { RawEvent } from "./types";

// Default blurhash per event type — warm festival tones
const BH: Record<string, string> = {
	correfoc: "L9C?Uo%M4,Iq~WNGE1WB4mWB9ZWB",
	focsartificials: "LB9]mvIU0z%M~WWBRjof0KWBIUj[",
	gegants: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	castellera: "L7B:Ix%M4nxt~qWB%MWBIUofRjof",
	concert: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
	cercavila: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	havaneres: "L4B:ItM{00IU~Wj[oej[4nj[NHoe",
	espectacle: "L9C?Uo%M4,Iq~WNGE1WB4mWB9ZWB",
	sardanes: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	exposicio: "L7C6P+%M4nxt~qWB%MWBxuofRjWB",
	missa: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
	default: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
};

// ISO helper – July 2026 dates, local time (month index 6 = July)
const d = (day: number, hour: number, min = 0): string =>
	new Date(2026, 6, day, hour, min, 0).toISOString();

// Next calendar day (for events that end after midnight)
const dn = (day: number, hour: number, min = 0): string =>
	new Date(2026, 6, day + 1, hour, min, 0).toISOString();

const LOC = {
	ajuntament: { lat: 41.539813, lng: 2.44490516 },
	basilica: { lat: 41.541, lng: 2.4468 },
	plSantaAnna: { lat: 41.5377, lng: 2.4447 },
	parcCentral: { lat: 41.5427, lng: 2.4379 },
	espaiLlar: { lat: 41.5459, lng: 2.4458 }, // Llar Cabanellas
	callao: { lat: 41.5343, lng: 2.4477 },
	maritim: { lat: 41.5392, lng: 2.4548 },
	port: { lat: 41.5325, lng: 2.4473 },
	tereses: { lat: 41.5384, lng: 2.4421 },
	monumental: { lat: 41.5438, lng: 2.4423 },
	biblioteca: { lat: 41.5385, lng: 2.446 },
	residencia: { lat: 41.5355, lng: 2.441 },
	esmandies: { lat: 41.538, lng: 2.4395 },
	plCuba: { lat: 41.5374, lng: 2.4409 },
	plSantaMaria: { lat: 41.5408, lng: 2.4463 },
	escorxador: { lat: 41.536, lng: 2.44 },
	preso: { lat: 41.5418, lng: 2.4434 },
};

const NAME = {
	ajuntament: "Ajuntament de Mataró",
	basilica: "Basílica de Santa Maria",
	plSantaAnna: "Pl. Santa Anna",
	parcCentral: "Nou Parc Central",
	espaiLlar: "Llar Cabanellas",
	callao: "Pl. de la Llibertat",
	maritim: "Passeig Marítim",
	port: "Port de Mataró",
	tereses: "Col·legi de les Tereses",
	monumental: "Teatre Municipal",
	biblioteca: "Biblioteca Pompeu Fabra",
	residencia: "Residència",
	esmandies: "Les Esmanadies",
	plCuba: "Pl. de Cuba",
	plSantaMaria: "Pl. de Santa Maria",
	escorxador: "Escorxador",
	preso: "La Presó",
};

export const MOCK_EVENTS: RawEvent[] = [
	// ─── JULY 18 (DIVENDRES) ────────────────────────────────────────────────
	{
		id: "e01",
		title: "Exposició de Kris Ubach",
		type: "exposicio",
		category: "cultural",
		icon: { name: "Image" },
		blurhash: "L6PZfSi_.AyE_3t7t7R**0o#DgR4",
		shortDescription:
			"Fotografies de la festa major 2024. Es pot veure fins al 7 de setembre a La Presó.",
		start: d(18, 19),
		end: d(18, 21),
		kind: "static",
		location: LOC.preso,
		locationName: NAME.preso,
	},
	{
		id: "e02",
		title: "Concert 50 anys del Cor Madrigalista",
		type: "concert",
		category: "cultural",
		icon: { name: "Mic" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription: "Acte gratuït amb invitació al Teatre Monumental.",
		start: d(18, 20),
		end: d(18, 22),
		kind: "static",
		location: LOC.monumental,
		locationName: NAME.monumental,
	},
	{
		id: "e03",
		title: "Assaig Castellers Capgrossos",
		type: "castellera",
		category: "tradicional",
		icon: { name: "Users" },
		blurhash: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
		shortDescription:
			"Últim assaig general dels Capgrossos de Mataró abans de l'actuació de Les Santes.",
		start: d(18, 20),
		end: d(18, 22),
		kind: "static",
		location: LOC.plSantaAnna,
		locationName: NAME.plSantaAnna,
	},
	{
		id: "e04",
		title: "Música: Ignorantes + Boom Boom Fighters",
		type: "concert",
		category: "nocturn",
		icon: { name: "Music" },
		blurhash: "L03_jN?bofj[~qj[j[j[D%j[Rjj[",
		shortDescription:
			"Concert a la plaça Santa Anna organitzat pels Capgrossos.",
		start: d(18, 23),
		end: dn(18, 1),
		kind: "static",
		location: LOC.plSantaAnna,
		locationName: NAME.plSantaAnna,
	},
	// ─── JULY 19 (DISSABTE) ─────────────────────────────────────────────────
	{
		id: "e05",
		title: "Proclama de Festa Major",
		type: "cercavila",
		category: "tradicional",
		icon: { name: "Megaphone" },
		blurhash: "L6B;DR-;IU?bx]t7t7WB-;_3t7WB",
		shortDescription:
			"L'alcalde encarrega a l'Herald la proclama de Festa Major. Recorregut per la Riera i places del centre.",
		start: d(19, 12),
		end: d(19, 13, 30),
		kind: "mobile",
		route: [
			{ lat: 41.539, lng: 2.4448 },
			{ lat: 41.5385, lng: 2.4443 },
			{ lat: 41.5375, lng: 2.4437 },
			{ lat: 41.5368, lng: 2.4422 },
			{ lat: 41.5375, lng: 2.4438 },
		],
	},
	{
		id: "e06",
		title: "Diada Castellera",
		type: "castellera",
		category: "tradicional",
		icon: { name: "Users" },
		blurhash: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
		shortDescription:
			"Amb la Colla Castellera Capgrossos de Mataró, els Minyons de Terrassa i els Castellers de Vilafranca.",
		start: d(19, 18),
		end: d(19, 21),
		kind: "static",
		location: LOC.plSantaAnna,
		locationName: NAME.plSantaAnna,
	},
	// ─── JULY 20 (DIUMENGE) ──────────────────────────────────────────────────
	{
		id: "e07",
		title: "L'Encesa",
		type: "correfoc",
		category: "nocturn",
		icon: { name: "Flame" },
		blurhash: "L9C?:H-;M{oL~qRjt7t7xuRjt7t7",
		shortDescription:
			"Balls parlats, cercavila de foc i encesa final amb el Ball de Diables de Mataró. Convidats: Seguici Festiu de Tarragona i els Basiliscs de Reus.",
		start: d(20, 18, 30),
		end: d(20, 22),
		kind: "mobile",
		route: [
			{ lat: 41.5375, lng: 2.4438 },
			{ lat: 41.5378, lng: 2.4432 },
			{ lat: 41.5368, lng: 2.4422 },
			{ lat: 41.5383, lng: 2.4443 },
			{ lat: 41.539, lng: 2.4448 },
		],
	},
	// ─── JULY 24 (DIJOUS) ────────────────────────────────────────────────────
	{
		id: "e08",
		title: "Gegantada",
		type: "gegants",
		category: "tradicional",
		icon: { name: "Crown" },
		blurhash: "L6B;DR-;IU?bx]t7t7WB-;_3t7WB",
		shortDescription:
			"Tots els gegants, nans i figures de la ciutat en una cercavila multitudinària. Sortida des de la Ronda O'Donnell.",
		start: d(24, 18),
		end: d(24, 20, 30),
		kind: "mobile",
		route: [
			{ lat: 41.5395, lng: 2.4465 },
			{ lat: 41.5392, lng: 2.4455 },
			{ lat: 41.5388, lng: 2.4448 },
			{ lat: 41.5385, lng: 2.4443 },
			{ lat: 41.5383, lng: 2.4438 },
			{ lat: 41.5375, lng: 2.4438 },
		],
	},
	{
		id: "e09",
		title: "Concert GospelSons",
		type: "concert",
		category: "cultural",
		icon: { name: "Mic" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription:
			"Concert de gospel a càrrec de la formació Gospelsons, que aquest any compleix 20 anys.",
		start: d(24, 20),
		end: d(24, 21, 30),
		kind: "static",
		location: LOC.callao,
		locationName: NAME.callao,
	},
	{
		id: "e10",
		title: "Havaneres i rom cremat",
		type: "havaneres",
		category: "tradicional",
		icon: { name: "Sailboat" },
		blurhash: "L4CQ:W?b0KMx~qt7t7WB00?bIU?b",
		shortDescription:
			"Amb Les Cremats i Arjau. No faltarà l'habitual rom cremat.",
		start: d(24, 22),
		end: dn(24, 0),
		kind: "static",
		location: LOC.callao,
		locationName: NAME.callao,
	},
	// ─── JULY 25 (DIVENDRES) ─────────────────────────────────────────────────
	{
		id: "e11",
		title: "Cap a la Crida",
		type: "cercavila",
		category: "tradicional",
		icon: { name: "Flag" },
		blurhash: "L6B;DR-;IU?bx]t7t7WB-;_3t7WB",
		shortDescription:
			"Comparses surten des de diversos indrets: Família Robafaves des del carrer Bonaire, Diablesses des de Sant Josep, Dracs des del carrer d'en Pujol.",
		start: d(25, 19, 45),
		end: d(25, 20),
		kind: "mobile",
		route: [
			{ lat: 41.5382, lng: 2.4432 },
			{ lat: 41.5385, lng: 2.4438 },
			{ lat: 41.539, lng: 2.4448 },
		],
	},
	{
		id: "e12",
		title: "Crida de Festa Major",
		type: "espectacle",
		category: "tradicional",
		icon: { name: "Megaphone" },
		blurhash: "L6B;DR-;IU?bx]t7t7WB-;_3t7WB",
		shortDescription:
			"L'alcalde proclama l'inici de la Festa Major des del balcó de l'Ajuntament. Una traca dóna pas als primers balls.",
		start: d(25, 20),
		end: d(25, 20, 30),
		kind: "static",
		location: LOC.ajuntament,
		locationName: NAME.ajuntament,
	},
	{
		id: "e13",
		title: "Desvetllament Bellugós",
		type: "cercavila",
		category: "nocturn",
		icon: { name: "Flag" },
		blurhash: "L03_jN?bofj[~qj[j[j[D%j[Rjj[",
		shortDescription:
			"La Família Robafaves baixa la Riera fins a la plaça Santa Anna a ritme de Bequetero.",
		start: d(25, 23, 30),
		end: dn(25, 0),
		kind: "mobile",
		route: [
			{ lat: 41.539, lng: 2.4448 },
			{ lat: 41.5385, lng: 2.4443 },
			{ lat: 41.5378, lng: 2.4438 },
			{ lat: 41.5375, lng: 2.4438 },
		],
	},
	{
		id: "e14",
		title: "Escapada a Negra Nit",
		type: "correfoc",
		category: "nocturn",
		icon: { name: "Flame" },
		blurhash: "L9C?:H-;M{oL~qRjt7t7xuRjt7t7",
		shortDescription:
			"Gran correfoc nocturn amb la Momerota, el Drac, les Diablesses i més de 15 colles convidades.",
		start: dn(25, 1, 30),
		end: dn(25, 3),
		kind: "mobile",
		route: [
			{ lat: 41.539, lng: 2.4448 },
			{ lat: 41.5383, lng: 2.4443 },
			{ lat: 41.5378, lng: 2.4432 },
			{ lat: 41.5372, lng: 2.4431 },
			{ lat: 41.5383, lng: 2.4443 },
			{ lat: 41.539, lng: 2.4448 },
		],
	},
	// ─── JULY 26 (DISSABTE) ─────────────────────────────────────────────────
	{
		id: "e15",
		title: "Música per la Diversitat",
		type: "concert",
		category: "cultural",
		icon: { name: "Music" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription:
			"Concert en el marc del Dia de l'Orgull LGTBIQ+. Diverses formacions musicals al Parc Central.",
		start: d(26, 19),
		end: d(26, 22),
		kind: "static",
		location: LOC.parcCentral,
		locationName: NAME.parcCentral,
	},
	{
		id: "e16",
		title: "Nit de Focs Artificials",
		type: "focsartificials",
		category: "nocturn",
		icon: { name: "Sparkles" },
		blurhash: "L9C?:H-;M{oL~qRjt7t7xuRjt7t7",
		shortDescription:
			"Castell de focs des del passeig marítim. Un dels espectacles més esperats de les festes.",
		start: d(26, 23),
		end: dn(26, 0),
		kind: "static",
		location: LOC.maritim,
		locationName: NAME.maritim,
	},
	// ─── JULY 27 (DIUMENGE - DEV DAY ref: 20:30) ────────────────────────────
	{
		id: "e17",
		title: "Toc de Matinades",
		type: "barram",
		category: "tradicional",
		icon: { name: "Bell" },
		blurhash: "L6PZfSi_.AyE_3t7t7R**0o#DgR4",
		shortDescription:
			"Repic de campanes per despertar la ciutat en el dia gran de les Santes",
		start: d(27, 6),
		end: d(27, 6, 30),
		kind: "static",
		location: LOC.basilica,
		locationName: NAME.basilica,
	},
	{
		id: "e18",
		title: "La Passada",
		type: "cercavila",
		category: "tradicional",
		icon: { name: "Flag" },
		blurhash: "L6B;DR-;IU?bx]t7t7WB-;_3t7WB",
		shortDescription:
			"Cercavila solemne des de l'Ajuntament fins a la Basílica de Santa Maria per La Riera",
		start: d(27, 17, 30),
		end: d(27, 21),
		kind: "mobile",

		route: [
			{ lat: 41.539754, lng: 2.445055 },
			{ lat: 41.539663, lng: 2.444724 },
			{ lat: 41.541168, lng: 2.444011 },
			{ lat: 41.540595, lng: 2.440122 },
			{ lat: 41.538858, lng: 2.442039 },
			{ lat: 41.538566, lng: 2.441491 },
			{ lat: 41.536506, lng: 2.443518 },
			{ lat: 41.536981, lng: 2.444018 },
			{ lat: 41.537203, lng: 2.44458 },
			{ lat: 41.537456, lng: 2.444418 },
			{ lat: 41.53814, lng: 2.444936 },
			{ lat: 41.53822, lng: 2.444846 },
			{ lat: 41.53845, lng: 2.444911 },
			{ lat: 41.53917, lng: 2.444842 },
			{ lat: 41.539601, lng: 2.444732 },
		],
	},
	{
		id: "e19",
		title: "Missa de les Santes",
		type: "missa",
		category: "tradicional",
		icon: { name: "Church" },
		blurhash: "L6PZfSi_.AyE_3t7t7R**0o#DgR4",
		shortDescription:
			"Missa pontifical a la Basílica. Més de 150 cantaires i orquestra simfònica",
		start: d(27, 10),
		end: d(27, 12),
		kind: "static",
		location: LOC.basilica,
		locationName: NAME.basilica,
	},
	{
		id: "e20",
		title: "Ballada de Sardanes",
		type: "sardanes",
		category: "tradicional",
		icon: { name: "Music" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription:
			"Ballada al carrer d'en Pujol. Cobla La Principal del Llobregat",
		start: d(27, 12),
		end: d(27, 14),
		kind: "static",
		location: { lat: 41.538, lng: 2.4442 },
		locationName: "Carrer d'en Pujol",
	},
	{
		id: "e21",
		title: "Postal de Gegants",
		type: "gegants",
		category: "tradicional",
		icon: { name: "Crown" },
		blurhash: "L6B;DR-;IU?bx]t7t7WB-;_3t7WB",
		shortDescription:
			"Exhibició dels gegants i nans de Mataró davant l'Ajuntament. Entrada lliure",
		start: d(27, 18, 30),
		end: d(27, 20),
		kind: "static",
		location: LOC.ajuntament,
		locationName: NAME.ajuntament,
	},
	{
		id: "e22",
		title: "La Processó de les Santes",
		type: "cercavila",
		category: "tradicional",
		icon: { name: "Star" },
		blurhash: "L6PZfSi_.AyE_3t7t7R**0o#DgR4",
		shortDescription:
			"Cercavila solemne amb les relíquies de les Santes pels carrers del centre",
		start: d(27, 18),
		end: d(27, 21),
		kind: "mobile",
		route: [
			{ lat: 41.539, lng: 2.4448 },
			{ lat: 41.5387, lng: 2.4445 },
			{ lat: 41.5382, lng: 2.444 },
			{ lat: 41.5378, lng: 2.4438 },
			{ lat: 41.5375, lng: 2.4432 },
			{ lat: 41.537, lng: 2.4425 },
			{ lat: 41.5368, lng: 2.442 },
		],
	},
	{
		id: "e23",
		title: "Espai Familiar - Nou Parc Central",
		type: "jocs",
		category: "familiar",
		icon: { name: "Smile" },
		blurhash: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
		shortDescription:
			"Tallers, jocs i espectacles per a tota la família. Animació infantil tot el vespre",
		start: d(27, 19),
		end: d(27, 22),
		kind: "static",
		location: LOC.parcCentral,
		locationName: NAME.parcCentral,
	},
	{
		id: "e24",
		title: "L'en hora del conte - Bigotis",
		type: "contes",
		category: "familiar",
		icon: { name: "BookOpen" },
		blurhash: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
		shortDescription:
			"Espectacle de contes per a infants de 3 a 8 anys. En català. Places limitades",
		start: d(27, 20, 15),
		end: d(27, 21),
		kind: "static",
		location: LOC.biblioteca,
		locationName: NAME.biblioteca,
	},
	{
		id: "e25",
		title: "Artilusio - Màgia i Circ",
		type: "espectacle",
		category: "familiar",
		icon: { name: "Wand2" },
		blurhash: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
		shortDescription:
			"Espectacle de circ i màgia al Teatre Municipal. Per a tots els públics",
		start: d(27, 19, 30),
		end: d(27, 21, 30),
		kind: "static",
		location: LOC.monumental,
		locationName: NAME.monumental,
	},
	{
		id: "e26",
		title: "Nit Boja - Correfoc de les Santes",
		type: "correfoc",
		category: "nocturn",
		icon: { name: "Flame" },
		blurhash: "L9C?:H-;M{oL~qRjt7t7xuRjt7t7",
		shortDescription:
			"El gran correfoc de la Nit Boja. Ball de Diables de Mataró i set colles convidades",
		start: d(27, 22),
		end: dn(27, 0, 30),
		kind: "mobile",
		route: [
			{ lat: 41.539, lng: 2.4448 },
			{ lat: 41.5385, lng: 2.4444 },
			{ lat: 41.538, lng: 2.444 },
			{ lat: 41.5374, lng: 2.4435 },
			{ lat: 41.5368, lng: 2.4428 },
			{ lat: 41.5362, lng: 2.4418 },
			{ lat: 41.5355, lng: 2.4408 },
		],
	},
	{
		id: "e27",
		title: "Concert al Parc: Mushkaa",
		type: "concert",
		category: "nocturn",
		icon: { name: "Mic" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription:
			"Concert de la banda Mushkaa al Nou Parc Central. Pop-rock en català",
		start: d(27, 21),
		end: d(27, 23),
		kind: "static",
		location: LOC.parcCentral,
		locationName: NAME.parcCentral,
	},
	{
		id: "e28",
		title: "Sardanes de la Nit",
		type: "sardanes",
		category: "nocturn",
		icon: { name: "Music" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription:
			"Ballada de sardanes de nit. Cobla La Principal del Llobregat. Repartiment de xíndria",
		start: d(27, 23, 45),
		end: dn(27, 2),
		kind: "static",
		location: LOC.plSantaAnna,
		locationName: NAME.plSantaAnna,
	},
	// ─── JULY 28 (DILLUNS) ───────────────────────────────────────────────────
	{
		id: "e29",
		title: "Balls Populars de les Santes",
		type: "sardanes",
		category: "tradicional",
		icon: { name: "Music" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription:
			"Balls de sardanes i ball de bot. Tarda festiva al centre de Mataró",
		start: d(28, 17),
		end: d(28, 20),
		kind: "static",
		location: LOC.plSantaAnna,
		locationName: NAME.plSantaAnna,
	},
	{
		id: "e30",
		title: "Diada Castellera de Sant Jaume",
		type: "castellera",
		category: "tradicional",
		icon: { name: "Users" },
		blurhash: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
		shortDescription:
			"Actuació castellera de la Colla Castellera de Mataró amb colles convidades",
		start: d(28, 18),
		end: d(28, 20, 30),
		kind: "static",
		location: LOC.plSantaAnna,
		locationName: NAME.plSantaAnna,
	},
	{
		id: "e31",
		title: "Havaneres i Cremat de Cloenda",
		type: "havaneres",
		category: "tradicional",
		icon: { name: "Sailboat" },
		blurhash: "L4CQ:W?b0KMx~qt7t7WB00?bIU?b",
		shortDescription:
			"Concert d'havaneres per cloure les festes. Cremat gratuït per a tothom. Passeig marítim",
		start: d(28, 21, 30),
		end: d(28, 23, 30),
		kind: "static",
		location: LOC.maritim,
		locationName: NAME.maritim,
	},
	// ─── JULY 29 (DIMARTS - DARRER DIA) ─────────────────────────────────────
	{
		id: "e32",
		title: "Cercavila de Cloenda",
		type: "cercavila",
		category: "tradicional",
		icon: { name: "Flag" },
		blurhash: "L6B;DR-;IU?bx]t7t7WB-;_3t7WB",
		shortDescription:
			"Cercavila final de les Santes amb gegants, gralles i entitats de la ciutat",
		start: d(29, 11),
		end: d(29, 13),
		kind: "mobile",
		route: [
			{ lat: 41.5375, lng: 2.4438 },
			{ lat: 41.5382, lng: 2.4443 },
			{ lat: 41.539, lng: 2.4448 },
			{ lat: 41.5395, lng: 2.445 },
		],
	},
	{
		id: "e33",
		title: "Concert de Cloenda: La Troba Kung-Fú",
		type: "concert",
		category: "nocturn",
		icon: { name: "Mic" },
		blurhash: "L4ADf900?bIU?bt7t7WB00-;RjWB",
		shortDescription:
			"Concert final de les Santes amb La Troba Kung-Fú. Entrada lliure fins a completar aforament",
		start: d(29, 22),
		end: dn(29, 0),
		kind: "static",
		location: LOC.parcCentral,
		locationName: NAME.parcCentral,
	},
];
