import type { EventCategory, EventIconDef, EventKind, EventType, RawEvent, RoutePoint, StaticLocation } from "./types";

/** Curated Unsplash photos per event type — free to hotlink with attribution */
export const IMAGE_BY_TYPE: Record<EventType, string> = {
	correfoc:       "https://uploads.lessantes.cat/uploads/medium/bbef407c8987d205751b00506f5b8d24.jpeg",  
	focsartificials:"https://uploads.lessantes.cat/uploads/medium/d4482e719acddb6243435e2fc6743087.jpeg",  
	gegants:        "https://uploads.lessantes.cat/uploads/big/4046d84b2488e6f22f2215aabda59ec6.jpeg?p=992",  
	castellera:     "https://uploads.lessantes.cat/uploads/medium/56a2f26b3193a14374e05c0654733ffb.jpeg", 
	concert:        "https://uploads.lessantes.cat/uploads/medium/30f3585c1a41e84e54d5ba9fb773dfb8.jpeg",
	cercavila:      "https://uploads.lessantes.cat/uploads/big/084294079db4bef328a2067a9c02ef84.jpeg?p=992",  
	havaneres:      "https://uploads.lessantes.cat/uploads/big/d51cb1d7276befa35d6efe62c17b9d2a.jpeg?p=992", 
	espectacle:     "https://uploads.lessantes.cat/uploads/medium/aef92804f2316232d534be8cbdf98ddd.jpeg",  
	sardanes:       "https://uploads.lessantes.cat/uploads/big/2864ecff970e16456bce811ca68129a5.jpeg?p=992", 
	exposicio:      "https://uploads.lessantes.cat/uploads/big/fcf2e18ce104464c6dbd16e62d51755f.jpeg?p=992", 
	missa:          "https://uploads.lessantes.cat/uploads/medium/ddbe51719b0d8445032c027c3cd99e52.jpeg",  
	cursa:          "https://uploads.lessantes.cat/uploads/big/d9eb5690322743e6d2d65fc6f7c1b073.jpeg?p=992", 
	jocs:           "https://uploads.lessantes.cat/uploads/medium/65ac14de2374353ad8c7d946d26bf767.jpeg",  
	contes:         "https://uploads.lessantes.cat/uploads/big/f7a9b5e06fe745c8a5d0e0ca49716ae5.jpeg?p=992", // storytelling / books
	barram:         "https://uploads.lessantes.cat/uploads/medium/842af0a80231abf733635778daa03be6.jpeg",  
	altres:         "https://uploads.lessantes.cat/uploads/medium/725fa18ecf54436ad936e6b9719f4ed4.jpeg", 
};

const BH: Record<EventType | "default", string> = {
	correfoc: "L9C?Uo%M4,Iq~WNGE1WB4mWB9ZWB",
	focsartificials: "LB9]mvIU0z%M~WWBRjof0KWBIUj[",
	gegants: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	castellera: "L7B:Ix%M4nxt~qWB%MWBIUofRjof",
	concert: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
	cercavila: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	havaneres: "L4B:ItM{00IU~Wj[oej[4nj[NHoe",
	espectacle: "L9C?Uo%M4,Iq~WNGE1WB4mWB9ZWB",
	sardanes: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	exposicio: "L7C6P+%M4nxt~qWB%MWBxuofRjWB",
	missa: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
	cursa: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	jocs: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
	contes: "L5H2EC=PM+yV0g-mq.wG9c010J}I",
	barram: "L6PZfSi_.AyE_3t7t7R**0o#DgR4",
	altres: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
	default: "L6Pj0^jE.AyE_3t7t7R**0o#DgR4",
};

const d = (day: number, hour: number, min = 0): string =>
	new Date(2026, 6, day, hour, min, 0).toISOString();

const dn = (day: number, hour: number, min = 0): string =>
	new Date(2026, 6, day + 1, hour, min, 0).toISOString();

const LOC = {
 	ajuntament: { lat: 41.5397828848703, lng: 2.444718276586209 },
	basilica: { lat: 41.540979, lng: 2.446309 },
	plSantaAnna: { lat: 41.537687, lng: 2.444657 },
	plSantaMaria: { lat: 41.540778, lng: 2.446272 },
	plCuba: { lat: 41.537373, lng: 2.440892 },
	canXammar: { lat: 41.538561, lng: 2.445205 },
	cPujol: { lat: 41.538239, lng: 2.444588 },
	parcCentral: { lat: 41.542709, lng: 2.437911 },
	espaiFiral: { lat: 41.543581, lng: 2.438094 },
	llarCabanellas: { lat: 41.545915, lng: 2.445812 },
	callao: { lat: 41.534321, lng: 2.447741 },
	maritim: { lat: 41.534831, lng: 2.453907 },
	port: { lat: 41.532508, lng: 2.447331 },
	varador: { lat: 41.535934, lng: 2.453779 },
	preso: { lat: 41.541775, lng: 2.443381 },
	monumental: { lat: 41.543811, lng: 2.442289 },
	biblioteca: { lat: 41.538524, lng: 2.446017 },
	residencia: { lat: 41.535542, lng: 2.441028 },
	esmandies: { lat: 41.538021, lng: 2.439495 },
	cafeNou: { lat: 41.539245, lng: 2.443169 },
	escorxador: { lat: 41.536011, lng: 2.440008 },
	destilleria: { lat: 41.537861, lng: 2.448898 },
	foment: { lat: 41.540063, lng: 2.445875 },
	canSerra: { lat: 41.540522, lng: 2.446517 },
	alianca: { lat: 41.539286, lng: 2.443571 },
	escolaVistaAlegre: { lat: 41.558453, lng: 2.437627 },
	marMediterrania: { lat: 41.554121, lng: 2.431667 },
	canMarfa: { lat: 41.541762, lng: 2.449796 },
} satisfies Record<string, StaticLocation>;

const NAME = {
	ajuntament: "Ajuntament de Mataró",
	basilica: "Basílica de Santa Maria",
	plSantaAnna: "Plaça de Santa Anna",
	plSantaMaria: "Plaça de Santa Maria",
	plCuba: "Plaça de Cuba",
	canXammar: "Plaça de Can Xammar",
	cPujol: "Carrer d'en Pujol",
	parcCentral: "Nou Parc Central",
	espaiFiral: "Espai Firal del Nou Parc Central",
	llarCabanellas: "Llar Cabanellas",
	callao: "Passeig del Callao",
	maritim: "Passeig Marítim",
	port: "Port de Mataró",
	varador: "Platja del Varador",
	preso: "M|A|C Presó",
	monumental: "Teatre Monumental",
	biblioteca: "Biblioteca Pompeu Fabra",
	residencia: "Pati de la Residència Sant Josep",
	esmandies: "Pati de les Esmandies",
	cafeNou: "Pati del Cafè Nou",
	escorxador: "Jardins de l'Antic Escorxador",
	destilleria: "La Destil·leria",
	foment: "Foment Mataroní",
	canSerra: "Can Serra. Museu de Mataró",
	alianca: "Casal L'Aliança",
	escolaVistaAlegre: "Escola Vista Alegre",
	marMediterrania: "Institut Escola Mar Mediterrània",
	canMarfa: "Can Marfà",
} satisfies Record<keyof typeof LOC, string>;

const ROUTES_PRIMITIVES = {
	riera: [LOC.ajuntament, 
		{ lat: 41.53967408030377, lng: 2.444709907423828 },
		{ lat: 41.539175994444776, lng: 2.444857486113847 },
		{ lat: 41.53865982884221, lng: 2.4449111510907926 },
		{ lat: 41.53822600553849, lng: 2.4448789521039203 },
		LOC.plSantaAnna]
}
const ROUTE_HELPERS = {
	rieraDown: ROUTES_PRIMITIVES.riera,
	rieraUp: ROUTES_PRIMITIVES.riera.slice().reverse(),
}

const ROUTE = {
	rieraDown:ROUTE_HELPERS.rieraDown,
	fireCenter: [LOC.ajuntament, { lat: 41.5388, lng: 2.4446 }, { lat: 41.5381, lng: 2.4441 }, LOC.canXammar, LOC.plSantaMaria, { lat: 41.5401, lng: 2.4458 }, LOC.ajuntament],
	ajuntamentToParc: [LOC.ajuntament, { lat: 41.5402, lng: 2.4437 }, { lat: 41.5411, lng: 2.4418 }, LOC.espaiFiral],
	ofici: [LOC.ajuntament, LOC.plSantaMaria, LOC.basilica],
	desfilada: [LOC.plSantaMaria, { lat: 41.5402, lng: 2.4459 }, LOC.ajuntament],
	passada: [
		LOC.ajuntament,
		{ lat: 41.53978244827795, lng: 2.444649239656343 },
		{ lat: 41.54114869982419, lng: 2.4440106498155387 },
		{ lat: 41.540603048644044, lng: 2.4401112959255045 },
		{ lat: 41.53886877788818, lng: 2.4420496703954484 },
		{ lat: 41.53858536824569, lng: 2.441512802830374 },
		{ lat: 41.538483848071905, lng: 2.44152410530549 },
		{ lat: 41.53799739502716, lng: 2.442021414207744 },
		{ lat: 41.537938174406975, lng: 2.442038367920361 },
		{ lat: 41.53715561111494, lng: 2.442835192410996 },
		{ lat: 41.53650840296828, lng: 2.4435189921507856 },
		{ lat: 41.53696525644989, lng: 2.4439993473404513 },
		{ lat: 41.537252903282706, lng: 2.4446831470802977 },
		{ lat: 41.53743902702237, lng: 2.444411887679621 },
		...ROUTE_HELPERS.rieraUp
	],
	residencia: [LOC.ajuntament, { lat: 41.5386, lng: 2.4435 }, LOC.residencia],
	residenciaBack: [LOC.residencia, { lat: 41.5386, lng: 2.4435 }, LOC.ajuntament],
	postal: [LOC.ajuntament, { lat: 41.5388, lng: 2.4444 }, { lat: 41.5379, lng: 2.4445 }, LOC.ajuntament],
	dracs: [LOC.plSantaMaria, { lat: 41.5401, lng: 2.4458 }, { lat: 41.5391, lng: 2.4449 }, LOC.ajuntament],
	tancar: [LOC.ajuntament, { lat: 41.5402, lng: 2.4458 }, LOC.plSantaMaria, { lat: 41.5411, lng: 2.4472 }, LOC.canMarfa],
} satisfies Record<string, RoutePoint[]>;

const iconForType: Record<EventType, EventIconDef> = {
	cercavila: { name: "Flag" },
	correfoc: { name: "Flame" },
	concert: { name: "Music" },
	sardanes: { name: "Music2" },
	castellera: { name: "Users" },
	gegants: { name: "Crown" },
	havaneres: { name: "Sailboat" },
	exposicio: { name: "Image" },
	espectacle: { name: "Theater" },
	missa: { name: "Church" },
	focsartificials: { name: "Sparkles" },
	cursa: { name: "Footprints" },
	jocs: { name: "Gamepad2" },
	contes: { name: "BookOpen" },
	barram: { name: "Bell" },
	altres: { name: "MapPin" },
};

type MockEventInput = {
	id: string;
	title: string;
	type: EventType;
	category: EventCategory;
	shortDescription: string;
	start: string;
	end: string;
	kind?: EventKind;
	locationKey?: keyof typeof LOC;
	locationName?: string;
	route?: RoutePoint[];
	icon?: EventIconDef;
	imageUrl?: string;
};

const event = ({
	id,
	title,
	type,
	category,
	shortDescription,
	start,
	end,
	kind = "static",
	locationKey,
	locationName,
	route,
	icon,
	imageUrl,
}: MockEventInput): RawEvent => {
	const base = {
		id,
		title,
		type,
		category,
		icon: icon ?? iconForType[type],
		blurhash: BH[type] ?? BH.default,
		shortDescription,
		start,
		end,
		imageUrl: imageUrl ?? IMAGE_BY_TYPE[type],
	};

	if (kind === "mobile") {
		if (!route) {
			throw new Error(`Mobile event "${id}" needs a route`);
		}

		return { ...base, kind, route, locationName };
	}

	if (!locationKey) {
		throw new Error(`Static event "${id}" needs a locationKey`);
	}

	return {
		...base,
		kind: "static",
		location: LOC[locationKey],
		locationName: locationName ?? NAME[locationKey],
	};
};

export const MOCK_EVENTS: RawEvent[] = [
	event({
		id: "ls25-001",
		title: "Signatura de cartells de Les Santes",
		type: "altres",
		category: "cultural",
		shortDescription: "Ana García Pérez signa el cartell oficial a la plaça de Santa Anna.",
		start: d(18, 18),
		end: d(18, 21),
		locationKey: "plSantaAnna",
		icon: { name: "PenLine" },
	}),
	event({
		id: "ls25-002",
		title: "Kris Ubach. Quan no són Santes",
		type: "exposicio",
		category: "cultural",
		shortDescription: "Inauguració de l'exposició fotogràfica al M|A|C Presó.",
		start: d(18, 19),
		end: d(18, 20),
		locationKey: "preso",
	}),
	event({
		id: "ls25-003",
		title: "Toc de Novena",
		type: "barram",
		category: "tradicional",
		shortDescription: "Toc de campanes a Santa Maria, cada tarda fins al 26 de juliol.",
		start: d(18, 19, 15),
		end: d(18, 19, 35),
		locationKey: "basilica",
	}),
	event({
		id: "ls25-004",
		title: "Cor Madrigalista. 50 anys",
		type: "concert",
		category: "cultural",
		shortDescription: "Concert extraordinari amb els directors que han marcat la trajectòria del cor.",
		start: d(18, 20),
		end: d(18, 22),
		locationKey: "monumental",
	}),
	event({
		id: "ls25-005",
		title: "Assaig de la Colla Castellera Capgrossos",
		type: "castellera",
		category: "tradicional",
		shortDescription: "Assaig obert dels Capgrossos de Mataró abans de la gran diada castellera.",
		start: d(18, 20),
		end: d(18, 22),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-006",
		title: "Anima't",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Curtmetratges familiars de l'alumnat de l'Escola Montserrat Solà.",
		start: d(18, 21, 30),
		end: d(18, 22, 30),
		locationKey: "preso",
		icon: { name: "Clapperboard" },
	}),
	event({
		id: "ls25-007",
		title: "The New Raemon and Leia Destruye",
		type: "concert",
		category: "nocturn",
		shortDescription: "Concert dins el cicle L'Hora del Pati al M|A|C Presó.",
		start: d(18, 23),
		end: dn(18, 0, 30),
		locationKey: "preso",
	}),
	event({
		id: "ls25-008",
		title: "Ignorantes + Boom Boom Fighters",
		type: "concert",
		category: "nocturn",
		shortDescription: "Primera nit musical amb reggae, latin, rock, punk, ska i dancehall.",
		start: d(18, 23),
		end: dn(18, 1),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-009",
		title: "L'evolució de la tenora en l'univers de la festa",
		type: "altres",
		category: "cultural",
		shortDescription: "Acte institucional de l'Estrena amb Miquel Puigdellívol i Enric Ortí.",
		start: d(19, 11),
		end: d(19, 12),
		locationKey: "ajuntament",
		icon: { name: "Landmark" },
	}),
	event({
		id: "ls25-010",
		title: "Proclama de Festa Major",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "L'Herald, les Trampes, els Flabiolaires i els abanderats anuncien la Festa Major.",
		start: d(19, 12),
		end: d(19, 13, 30),
		kind: "mobile",
		route: ROUTE.rieraDown,
	}),
	event({
		id: "ls25-011",
		title: "Jocs d'en Santi",
		type: "jocs",
		category: "familiar",
		shortDescription: "Dissantes infantils amb jocs, tallers, circuit de mobilitat i circuit sensorial.",
		start: d(19, 11),
		end: d(19, 20, 30),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-012",
		title: "Diada Castellera",
		type: "castellera",
		category: "tradicional",
		shortDescription: "Capgrossos de Mataró, Minyons de Terrassa i Castellers de Vilafranca.",
		start: d(19, 18),
		end: d(19, 21),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-013",
		title: "Vespreig amb PD Bingos",
		type: "concert",
		category: "nocturn",
		shortDescription: "Sessió musical al Pati del Cafè Nou dins les Dissantes.",
		start: d(19, 18, 30),
		end: d(19, 20, 30),
		locationKey: "cafeNou",
		icon: { name: "Disc3" },
	}),
	event({
		id: "ls25-014",
		title: "Flashmob Dissantes",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Flashmob amb Wiz Problema i Mama Dousha al Nou Parc Central.",
		start: d(19, 21),
		end: d(19, 22),
		locationKey: "espaiFiral",
		icon: { name: "Accessibility" },
	}),
	event({
		id: "ls25-015",
		title: "Concerts Dissantes",
		type: "concert",
		category: "nocturn",
		shortDescription: "Mama Dousha, Hotel Cochambre i DJ Lin tanquen la nit de Dissantes.",
		start: d(19, 22, 30),
		end: dn(19, 2),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-016",
		title: "32a Travessa nedant al port",
		type: "cursa",
		category: "cultural",
		shortDescription: "Prova esportiva amb sortides a les 9.15 h i a les 10 h.",
		start: d(20, 9, 15),
		end: d(20, 11),
		locationKey: "port",
		icon: { name: "Waves" },
	}),
	event({
		id: "ls25-017",
		title: "Les Misérables",
		type: "espectacle",
		category: "cultural",
		shortDescription: "Producció musical de l'Orquestra de Mataró en versió original anglesa.",
		start: d(20, 11, 30),
		end: d(20, 13, 30),
		locationKey: "monumental",
	}),
	event({
		id: "ls25-018",
		title: "L'Encesa",
		type: "correfoc",
		category: "tradicional",
		shortDescription: "Cercavila infantil, presentació del Basilisc Petit, ball parlat i encesa final.",
		start: d(20, 18, 30),
		end: d(20, 22),
		kind: "mobile",
		route: ROUTE.fireCenter,
	}),
	event({
		id: "ls25-019",
		title: "Oh! Quin dia a la granja!",
		type: "contes",
		category: "familiar",
		shortDescription: "Hora del conte especial amb Anima Theatrum.",
		start: d(22, 18),
		end: d(22, 19),
		locationKey: "biblioteca",
	}),
	event({
		id: "ls25-020",
		title: "Broadway Santes",
		type: "espectacle",
		category: "cultural",
		shortDescription: "Clàssics del teatre musical amb la companyia Suerte en mi vida.",
		start: d(23, 19),
		end: d(23, 20, 15),
		locationKey: "monumental",
	}),
	event({
		id: "ls25-021",
		title: "Gegantada",
		type: "gegants",
		category: "tradicional",
		shortDescription: "Trobada gegantera de la ciutat, des de la ronda d'O'Donnell fins a Santa Anna.",
		start: d(24, 18),
		end: d(24, 20, 30),
		kind: "mobile",
		route: [{ lat: 41.5395, lng: 2.4465 }, { lat: 41.5392, lng: 2.4455 }, LOC.plSantaAnna],
	}),
	event({
		id: "ls25-022",
		title: "Visita guiada: Kris Ubach. Quan no són Santes",
		type: "exposicio",
		category: "cultural",
		shortDescription: "Visita guiada a l'exposició fotogràfica de Les Santes.",
		start: d(24, 19),
		end: d(24, 20),
		locationKey: "preso",
	}),
	event({
		id: "ls25-023",
		title: "H",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Espectacle aeri de funambulisme de Cia. La Corcoles.",
		start: d(24, 19),
		end: d(24, 19, 45),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-024",
		title: "Forat",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Espectacle de clown de Dudu Arnalot a l'Espai Familiar.",
		start: d(24, 20),
		end: d(24, 20, 45),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-025",
		title: "GospelSons",
		type: "concert",
		category: "cultural",
		shortDescription: "Concert de gòspel pel 25è aniversari de la formació.",
		start: d(24, 20),
		end: d(24, 21, 30),
		locationKey: "callao",
	}),
	event({
		id: "ls25-026",
		title: "Express",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Circ fresc i dinàmic de Cía. Faltan 7.",
		start: d(24, 21),
		end: d(24, 21, 50),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-027",
		title: "Artefacto 71",
		type: "espectacle",
		category: "cultural",
		shortDescription: "Videoart de Carlos Essmann i Martí Anson dins L'Hora del Pati.",
		start: d(24, 21, 45),
		end: d(24, 22, 45),
		locationKey: "preso",
		icon: { name: "Projector" },
	}),
	event({
		id: "ls25-028",
		title: "Havaneres i rom cremat",
		type: "havaneres",
		category: "tradicional",
		shortDescription: "Els Cremats i Arjau posen música a la nit marinera del Callao.",
		start: d(24, 22),
		end: dn(24, 0),
		locationKey: "callao",
	}),
	event({
		id: "ls25-029",
		title: "1987",
		type: "concert",
		category: "nocturn",
		shortDescription: "Concert al pati del M|A|C Presó.",
		start: d(24, 23),
		end: dn(24, 0, 30),
		locationKey: "preso",
	}),
	event({
		id: "ls25-030",
		title: "Banda de l'Agrupació Musical del Maresme",
		type: "concert",
		category: "cultural",
		shortDescription: "Concert al pati de la Residència Sant Josep amb repertori de banda.",
		start: d(25, 18),
		end: d(25, 19),
		locationKey: "residencia",
	}),
	event({
		id: "ls25-031",
		title: "La màgia dels colors",
		type: "contes",
		category: "familiar",
		shortDescription: "Hora del conte amb Isabel Sanmartín i Montse Panero.",
		start: d(25, 18, 15),
		end: d(25, 19),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-032",
		title: "Quan torni la primavera",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Circ Pistolet presenta un viatge amb acrobàcies, humor i tendresa.",
		start: d(25, 19),
		end: d(25, 19, 50),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-033",
		title: "Catalunya Freestyle",
		type: "espectacle",
		category: "cultural",
		shortDescription: "Classificatòria oficial de freestyle en català al Nou Parc Central.",
		start: d(25, 18, 30),
		end: d(25, 23, 30),
		locationKey: "espaiFiral",
		icon: { name: "Mic2" },
	}),
	event({
		id: "ls25-034",
		title: "Cap a la Crida",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "Les comparses institucionals es dirigeixen cap a l'Ajuntament des de diversos indrets.",
		start: d(25, 19, 45),
		end: d(25, 20),
		kind: "mobile",
		route: ROUTE.rieraDown.slice(0, 3),
	}),
	event({
		id: "ls25-035",
		title: "Crida de Festa Major",
		type: "espectacle",
		category: "tradicional",
		shortDescription: "Crida de l'alcalde, traca i primers balls propis de les comparses.",
		start: d(25, 20),
		end: d(25, 20, 45),
		locationKey: "ajuntament",
		icon: { name: "Megaphone" },
	}),
	event({
		id: "ls25-036",
		title: "L'elefant Mainú i l'amistat",
		type: "contes",
		category: "familiar",
		shortDescription: "Segona hora del conte del dia a la Llar Cabanellas.",
		start: d(25, 20, 15),
		end: d(25, 21),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-037",
		title: "Harreman",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Dansa, circ i música tradicional basca amb Cia. Zirkozaurre.",
		start: d(25, 21),
		end: d(25, 21, 55),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-038",
		title: "Festival Flic",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Curtmetratges familiars: Vainilla i altres curts.",
		start: d(25, 21, 30),
		end: d(25, 22, 30),
		locationKey: "preso",
		icon: { name: "Clapperboard" },
	}),
	event({
		id: "ls25-039",
		title: "Los Aurora",
		type: "concert",
		category: "nocturn",
		shortDescription: "Flamenc, jazz, rock i música tradicional a la Llar Cabanellas.",
		start: d(25, 23),
		end: dn(25, 0, 15),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-040",
		title: "Desvetllament Bellugós",
		type: "gegants",
		category: "nocturn",
		shortDescription: "La Família Robafaves baixa La Riera al so del Bequetero.",
		start: d(25, 23, 30),
		end: dn(25, 0),
		kind: "mobile",
		route: ROUTE.rieraDown,
	}),
	event({
		id: "ls25-041",
		title: "Convidada de la Família Robafaves",
		type: "concert",
		category: "nocturn",
		shortDescription: "Germà Negre posa música a la mitjanit de la Nit Boja.",
		start: dn(25, 0),
		end: dn(25, 1),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-042",
		title: "Citto",
		type: "concert",
		category: "nocturn",
		shortDescription: "Concert de l'artista guanyador de la 0830X Block Party 2026.",
		start: dn(25, 0),
		end: dn(25, 1),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-043",
		title: "DJ Òscar",
		type: "concert",
		category: "nocturn",
		shortDescription: "Sessió musical al Nou Parc Central abans de La Ruixada.",
		start: dn(25, 1),
		end: dn(25, 3, 30),
		locationKey: "espaiFiral",
		icon: { name: "Disc3" },
	}),
	event({
		id: "ls25-044",
		title: "Escapada a Negra Nit",
		type: "correfoc",
		category: "nocturn",
		shortDescription: "Momerota, Drac, Diablesses i colles convidades en el gran correfoc nocturn.",
		start: dn(25, 1, 30),
		end: dn(25, 3),
		kind: "mobile",
		route: ROUTE.fireCenter,
	}),
	event({
		id: "ls25-045",
		title: "Pujada Tabalada",
		type: "cercavila",
		category: "nocturn",
		shortDescription: "Tabalers del Drac, de la Momerota i do Maresme pugen fins al Parc Central.",
		start: dn(25, 3),
		end: dn(25, 4),
		kind: "mobile",
		route: ROUTE.ajuntamentToParc,
		icon: { name: "Drum" },
	}),
	event({
		id: "ls25-046",
		title: "La Ruixada",
		type: "espectacle",
		category: "nocturn",
		shortDescription: "So, llum, aigua i èxits per tancar la Nit Boja al Nou Parc Central.",
		start: dn(25, 4),
		end: dn(25, 6),
		locationKey: "espaiFiral",
		icon: { name: "Waves" },
	}),
	event({
		id: "ls25-047",
		title: "Gegants i nans passats per aigua",
		type: "jocs",
		category: "familiar",
		shortDescription: "Taller familiar al M|A|C Presó.",
		start: d(26, 10),
		end: d(26, 14),
		locationKey: "preso",
	}),
	event({
		id: "ls25-048",
		title: "Concert vermut Muchalaka",
		type: "concert",
		category: "cultural",
		shortDescription: "Rumba i barreja d'estils al pati de Les Esmandies.",
		start: d(26, 12),
		end: d(26, 13, 30),
		locationKey: "esmandies",
	}),
	event({
		id: "ls25-049",
		title: "Concert de Barram",
		type: "concert",
		category: "tradicional",
		shortDescription: "Trèvol actua al pati de la Residència Sant Josep abans de les campanes.",
		start: d(26, 12),
		end: d(26, 13, 45),
		locationKey: "residencia",
	}),
	event({
		id: "ls25-050",
		title: "Barram i repicada",
		type: "barram",
		category: "tradicional",
		shortDescription: "Toc manual de campanes i morterets de la vigília de Les Santes.",
		start: d(26, 14),
		end: d(26, 14, 30),
		locationKey: "basilica",
	}),
	event({
		id: "ls25-051",
		title: "Recepció oficial de les Julianes i les Sempronianes",
		type: "altres",
		category: "tradicional",
		shortDescription: "Recepció institucional al Saló de Sessions de l'Ajuntament.",
		start: d(26, 17),
		end: d(26, 18),
		locationKey: "ajuntament",
		icon: { name: "Landmark" },
	}),
	event({
		id: "ls25-052",
		title: "De parranda!",
		type: "gegants",
		category: "familiar",
		shortDescription: "La Família Robafaves baixa La Riera en la tarda guillada.",
		start: d(26, 18),
		end: d(26, 18, 30),
		kind: "mobile",
		route: ROUTE.rieraDown,
	}),
	event({
		id: "ls25-053",
		title: "Convidadeta de la Família Robafaves",
		type: "concert",
		category: "familiar",
		shortDescription: "Ball infantil amb La Tresca i la Verdesca.",
		start: d(26, 18, 30),
		end: d(26, 19, 45),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-054",
		title: "Contes d'àvies d'estar per casa",
		type: "contes",
		category: "familiar",
		shortDescription: "Hora del conte amb Laura Asensio.",
		start: d(26, 18, 15),
		end: d(26, 19),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-055",
		title: "Rústica",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Espectacle de dansa de Cia. Jove Dans Invitro.",
		start: d(26, 19),
		end: d(26, 19, 45),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-056",
		title: "Coral La Nota",
		type: "concert",
		category: "cultural",
		shortDescription: "Nou repertori de la coral amb clàssics i musicals.",
		start: d(26, 19, 30),
		end: d(26, 21),
		locationKey: "residencia",
	}),
	event({
		id: "ls25-057",
		title: "Correguspira",
		type: "correfoc",
		category: "familiar",
		shortDescription: "Correfoc infantil amb Momeroteta, Dragalió i colles convidades.",
		start: d(26, 20),
		end: d(26, 21, 30),
		kind: "mobile",
		route: ROUTE.fireCenter,
	}),
	event({
		id: "ls25-058",
		title: "El meu gran amic",
		type: "contes",
		category: "familiar",
		shortDescription: "Segona hora del conte de dissabte a l'Espai Familiar.",
		start: d(26, 20, 15),
		end: d(26, 21),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-059",
		title: "Cicatrius",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Dansa inclusiva i música en directe de Vero Cendoya.",
		start: d(26, 21),
		end: d(26, 22),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-060",
		title: "Les Santrash",
		type: "concert",
		category: "nocturn",
		shortDescription: "Proposta musical i performativa als Jardins de l'Antic Escorxador.",
		start: d(26, 21),
		end: dn(26, 1),
		locationKey: "escorxador",
	}),
	event({
		id: "ls25-061",
		title: "Pujada Tabaladeta",
		type: "cercavila",
		category: "familiar",
		shortDescription: "Els tabalers del Dragalió i de la Momerota pugen fins al Parc Central.",
		start: d(26, 22),
		end: d(26, 22, 30),
		kind: "mobile",
		route: ROUTE.ajuntamentToParc,
		icon: { name: "Drum" },
	}),
	event({
		id: "ls25-062",
		title: "Ballada de sardanes",
		type: "sardanes",
		category: "tradicional",
		shortDescription: "Ballada festiva amb la Cobla Contemporània.",
		start: d(26, 22),
		end: d(26, 23, 30),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-063",
		title: "La Ruixadeta",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Música, llum i aigua per als petits santeros i santeres.",
		start: d(26, 22, 30),
		end: d(26, 23, 30),
		locationKey: "espaiFiral",
		icon: { name: "Waves" },
	}),
	event({
		id: "ls25-064",
		title: "Carola Ortiz",
		type: "concert",
		category: "cultural",
		shortDescription: "Cantareras revisita la tradició oral femenina amb folk, jazz i electrònica.",
		start: d(26, 23),
		end: dn(26, 0, 15),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-065",
		title: "Revetlla de Festa Major",
		type: "concert",
		category: "nocturn",
		shortDescription: "Orquestra Di-Versiones, The Aguateques i Les Reines del Mambo.",
		start: d(26, 23, 30),
		end: dn(26, 3),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-066",
		title: "Arquitectura sonocromàtica",
		type: "espectacle",
		category: "cultural",
		shortDescription: "Espectacle performàtic de Neil Harbisson i Pol Lombarde.",
		start: dn(26, 0),
		end: dn(26, 1),
		locationKey: "preso",
		icon: { name: "Projector" },
	}),
	event({
		id: "ls25-067",
		title: "Matinades",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "Grups de grallers anuncien la Diada de Les Santes pels carrers.",
		start: d(27, 7),
		end: d(27, 8, 30),
		kind: "mobile",
		route: ROUTE.rieraDown,
		icon: { name: "Sunrise" },
	}),
	event({
		id: "ls25-068",
		title: "Toc d'Ofici",
		type: "barram",
		category: "tradicional",
		shortDescription: "Campaners de Santa Maria fan el toc d'ofici des del campanar.",
		start: d(27, 9),
		end: d(27, 9, 30),
		locationKey: "basilica",
	}),
	event({
		id: "ls25-069",
		title: "Anada a Ofici",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "Comparses, autoritats i la Banda van de l'Ajuntament a Santa Maria.",
		start: d(27, 9, 30),
		end: d(27, 10),
		kind: "mobile",
		route: ROUTE.ofici,
	}),
	event({
		id: "ls25-070",
		title: "Missa de les Santes",
		type: "missa",
		category: "tradicional",
		shortDescription: "Ofici dedicat a Santa Juliana i Santa Semproniana amb la Missa de Glòria.",
		start: d(27, 10),
		end: d(27, 12),
		locationKey: "basilica",
	}),
	event({
		id: "ls25-071",
		title: "Ballada de sardanes",
		type: "sardanes",
		category: "tradicional",
		shortDescription: "Cobla Ciutat de Granollers al carrer d'en Pujol.",
		start: d(27, 12),
		end: d(27, 13),
		locationKey: "cPujol",
	}),
	event({
		id: "ls25-072",
		title: "Desfilada",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "La comitiva torna de Santa Maria a l'Ajuntament amb balls propis.",
		start: d(27, 13),
		end: d(27, 14),
		kind: "mobile",
		route: ROUTE.desfilada,
	}),
	event({
		id: "ls25-073",
		title: "La Passada",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "La gran cercavila de comparses del dia de Les Santes.",
		start: d(27, 18),
		end: d(27, 21),
		kind: "mobile",
		route: ROUTE.passada,
	}),
	event({
		id: "ls25-074",
		title: "Capses per explicar",
		type: "contes",
		category: "familiar",
		shortDescription: "Hora del conte amb Laberta Delpoblet.",
		start: d(27, 18, 15),
		end: d(27, 19),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-075",
		title: "Artilusio",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Teatre d'objectes de Cía. Markeliñe sobre la màgia de la lectura.",
		start: d(27, 19),
		end: d(27, 19, 55),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-076",
		title: "Bigotis, quina festa!",
		type: "contes",
		category: "familiar",
		shortDescription: "Hora del conte de Les Santes amb Laberta Delpoblet.",
		start: d(27, 20, 15),
		end: d(27, 21),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-077",
		title: "Empaque",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Dansa, circ i flamenc amb Chicharrón Circo Flamenco.",
		start: d(27, 21),
		end: d(27, 22),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-078",
		title: "Castell de focs",
		type: "focsartificials",
		category: "nocturn",
		shortDescription: "Espectacle pirotècnic des del Varador, Mar Mediterrània i Vista Alegre.",
		start: d(27, 23),
		end: d(27, 23, 25),
		locationKey: "varador",
	}),
	event({
		id: "ls25-079",
		title: "Baix a Marc",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Música i animació al passeig amb Always Drinking, Cavalls, Girafes i Pep Callau.",
		start: d(27, 23, 45),
		end: dn(27, 1),
		locationKey: "maritim",
	}),
	event({
		id: "ls25-080",
		title: "Sardanes i xindriada",
		type: "sardanes",
		category: "nocturn",
		shortDescription: "Cobla La Principal del Llobregat, Cobla Ciutat de Girona i repartiment de xíndria.",
		start: d(27, 23, 45),
		end: dn(27, 1, 30),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-081",
		title: "Big Band Jazz Maresme & Adrian Cunningham",
		type: "concert",
		category: "cultural",
		shortDescription: "Swing i jazz clàssic a l'escenari de dalt de la Llar Cabanellas.",
		start: dn(27, 0),
		end: dn(27, 1, 15),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-082",
		title: "Mushka + Llum + DJ Maki",
		type: "concert",
		category: "nocturn",
		shortDescription: "Gran concert de Les Santes amb veus de l'escena urbana i pop nacional.",
		start: dn(27, 0),
		end: dn(27, 3),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-083",
		title: "45a Cursa Popular Les Santes",
		type: "cursa",
		category: "cultural",
		shortDescription: "Cinc quilòmetres amb sortida i arribada al Nou Parc Central.",
		start: d(28, 9),
		end: d(28, 10),
		locationKey: "parcCentral",
	}),
	event({
		id: "ls25-084",
		title: "Anada a la Residència Sant Josep",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "Comparses, autoritats i la Banda visiten la gent gran de la Residència.",
		start: d(28, 10, 30),
		end: d(28, 11, 30),
		kind: "mobile",
		route: ROUTE.residencia,
	}),
	event({
		id: "ls25-085",
		title: "Ballada de sardanes",
		type: "sardanes",
		category: "tradicional",
		shortDescription: "La Principal de la Bisbal acompanya el matí a la Residència Sant Josep.",
		start: d(28, 11, 30),
		end: d(28, 13),
		locationKey: "residencia",
	}),
	event({
		id: "ls25-086",
		title: "Tornada a l'Ajuntament",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "Les comparses tornen de la Residència a l'Ajuntament.",
		start: d(28, 13, 30),
		end: d(28, 14, 15),
		kind: "mobile",
		route: ROUTE.residenciaBack,
	}),
	event({
		id: "ls25-087",
		title: "Contes dins d'una ampolla",
		type: "contes",
		category: "familiar",
		shortDescription: "Hora del conte amb Santi Rovira.",
		start: d(28, 18, 15),
		end: d(28, 19),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-088",
		title: "Postal de Gegants",
		type: "gegants",
		category: "tradicional",
		shortDescription: "Família Robafaves i Gegants Nous de Terrassa celebren l'aniversari del casament.",
		start: d(28, 18, 30),
		end: d(28, 20, 30),
		kind: "mobile",
		route: ROUTE.postal,
	}),
	event({
		id: "ls25-089",
		title: "Domte",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Nacho Flores juga amb estructures, gravetat, pesos i equilibris.",
		start: d(28, 19),
		end: d(28, 19, 50),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-090",
		title: "Concert de sardanes",
		type: "sardanes",
		category: "tradicional",
		shortDescription: "Concert de La Principal de la Bisbal a la Residència Sant Josep.",
		start: d(28, 19, 15),
		end: d(28, 20, 30),
		locationKey: "residencia",
	}),
	event({
		id: "ls25-091",
		title: "En clau de sol",
		type: "contes",
		category: "familiar",
		shortDescription: "Segona hora del conte de dilluns amb Santi Rovira.",
		start: d(28, 20, 15),
		end: d(28, 21),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-092",
		title: "Revolució",
		type: "espectacle",
		category: "familiar",
		shortDescription: "Teatro Sobre Ruedas combina circ, humor i música en directe.",
		start: d(28, 21),
		end: d(28, 22),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-093",
		title: "Ball de Dracs",
		type: "correfoc",
		category: "tradicional",
		shortDescription: "Drac, Dragalió i Dracs dels Monjos ballen pel centre de la ciutat.",
		start: d(28, 21, 30),
		end: d(28, 22, 30),
		kind: "mobile",
		route: ROUTE.dracs,
	}),
	event({
		id: "ls25-094",
		title: "Momi Maiga",
		type: "concert",
		category: "cultural",
		shortDescription: "L'artista senegalès presenta Kairo a la Llar Cabanellas.",
		start: d(28, 23),
		end: dn(28, 0, 15),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-095",
		title: "Requisits de Festa Major",
		type: "concert",
		category: "nocturn",
		shortDescription: "Ball d'envelat amb La Principal de la Bisbal i degustació de Juliana.",
		start: d(28, 23),
		end: dn(28, 2),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-096",
		title: "La Festa de la Juliana",
		type: "espectacle",
		category: "cultural",
		shortDescription: "Espectacle performàtic de Neus Masdeu dins L'Hora del Pati.",
		start: dn(28, 0),
		end: dn(28, 1),
		locationKey: "preso",
		icon: { name: "Projector" },
	}),
	event({
		id: "ls25-097",
		title: "DJ Nilvard",
		type: "concert",
		category: "nocturn",
		shortDescription: "Sessió musical a la plaça de Santa Anna.",
		start: dn(28, 2),
		end: dn(28, 4),
		locationKey: "plSantaAnna",
		icon: { name: "Disc3" },
	}),
	event({
		id: "ls25-098",
		title: "No n'hi ha prou!",
		type: "cercavila",
		category: "nocturn",
		shortDescription: "Diablesses, Momerota, Drac, Àliga i Família Robafaves ballen davant l'Ajuntament.",
		start: dn(28, 2),
		end: dn(28, 3, 30),
		locationKey: "ajuntament",
		icon: { name: "Flame" },
	}),
	event({
		id: "ls25-099",
		title: "Vermut de Bastons",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "Ball de Bastons de Mataró i Bastoners de Mataró fan recorregut amb tastets.",
		start: d(29, 12, 30),
		end: d(29, 14),
		kind: "mobile",
		route: [LOC.plCuba, { lat: 41.53765, lng: 2.4419 }, { lat: 41.5382, lng: 2.443 }],
		icon: { name: "Beer" },
	}),
	event({
		id: "ls25-100",
		title: "Enfigura't",
		type: "jocs",
		category: "familiar",
		shortDescription: "Activitat per provar figures i conèixer les comparses de Mataró.",
		start: d(29, 18),
		end: d(29, 19, 15),
		locationKey: "ajuntament",
	}),
	event({
		id: "ls25-101",
		title: "B.O.M. Contes de bruixes, ogres i monstres",
		type: "contes",
		category: "familiar",
		shortDescription: "Hora del conte amb Mon Mas.",
		start: d(29, 18, 15),
		end: d(29, 19),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-102",
		title: "Anem a tancar",
		type: "cercavila",
		category: "tradicional",
		shortDescription: "Última passejada, últims balls i última dormida fins a Can Marfà.",
		start: d(29, 19, 15),
		end: d(29, 21),
		kind: "mobile",
		route: ROUTE.tancar,
	}),
	event({
		id: "ls25-103",
		title: "L'illa d'en Lluís",
		type: "contes",
		category: "familiar",
		shortDescription: "Segona sessió de contes de Mon Mas a l'Espai Familiar.",
		start: d(29, 19, 15),
		end: d(29, 20),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari Contes",
	}),
	event({
		id: "ls25-104",
		title: "Concert de Festa Major",
		type: "concert",
		category: "cultural",
		shortDescription: "Orquestra Maravella amenitza la tarda al Nou Parc Central.",
		start: d(29, 19, 30),
		end: d(29, 21),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-105",
		title: "Bon vent",
		type: "concert",
		category: "familiar",
		shortDescription: "Concert familiar d'Ebri Knight dedicat a l'esperit de Xesco Boix.",
		start: d(29, 20),
		end: d(29, 21),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de baix",
	}),
	event({
		id: "ls25-106",
		title: "Concerts Marrinxa",
		type: "concert",
		category: "nocturn",
		shortDescription: "Sound System, Lepanto 41, Pussil de Asalto, Blú Versions i PD Bingos.",
		start: d(29, 21),
		end: dn(29, 2),
		locationKey: "plSantaAnna",
	}),
	event({
		id: "ls25-107",
		title: "Botifarra a Banda",
		type: "concert",
		category: "cultural",
		shortDescription: "Banda de l'Agrupació Musical del Maresme amb Pep Gimeno Botifarra.",
		start: d(29, 22),
		end: d(29, 23, 30),
		locationKey: "llarCabanellas",
		locationName: "Llar Cabanellas. Escenari de dalt",
	}),
	event({
		id: "ls25-108",
		title: "Tronada de fi de festa",
		type: "focsartificials",
		category: "nocturn",
		shortDescription: "Cinc minuts de màxima intensitat pirotècnica al Nou Parc Central.",
		start: dn(29, 0),
		end: dn(29, 0, 10),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-109",
		title: "Espetec final",
		type: "concert",
		category: "nocturn",
		shortDescription: "Últim ball amb Orquestra Maravella i D'Spoilers.",
		start: dn(29, 0, 10),
		end: dn(29, 5, 30),
		locationKey: "espaiFiral",
	}),
	event({
		id: "ls25-110",
		title: "Paraules d'amor",
		type: "espectacle",
		category: "cultural",
		shortDescription: "Videoart i música de Núria Güell dins L'Hora del Pati.",
		start: dn(29, 0, 15),
		end: dn(29, 1, 15),
		locationKey: "preso",
		icon: { name: "Projector" },
	}),
	event({
		id: "ls25-111",
		title: "L'Albada",
		type: "cercavila",
		category: "nocturn",
		shortDescription: "Los Labradores acomiaden Les Santes camí de la plaça de Santa Anna.",
		start: dn(29, 6),
		end: dn(29, 7),
		kind: "mobile",
		route: [LOC.espaiFiral, { lat: 41.5412, lng: 2.4418 }, { lat: 41.5392, lng: 2.4438 }, LOC.plSantaAnna],
		icon: { name: "Sunrise" },
	}),
];
